// flow-typed signature: c72bc1ce0a68675be17b397d4baf8443
// flow-typed version: <<STUB>>/docx_v^4.7.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docx/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docx/build/index.js' {
  declare module.exports: $Exports<'docx/build/index'>;
}
