// flow-typed signature: a521017213ebc8d7308f9a0269f89fe1
// flow-typed version: <<STUB>>/promise-deferred_v^2.0.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-deferred'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-deferred' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promise-deferred/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promise-deferred/index' {
  declare module.exports: $Exports<'promise-deferred'>;
}
declare module 'promise-deferred/index.js' {
  declare module.exports: $Exports<'promise-deferred'>;
}
declare module 'promise-deferred/test.js' {
  declare module.exports: $Exports<'promise-deferred/test'>;
}
