// flow-typed signature: 116b1447958dc41f06cfc8db98883868
// flow-typed version: <<STUB>>/react-dropzone-component_v^3.2.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropzone-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropzone-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dropzone-component/dist/react-dropzone' {
  declare module.exports: any;
}

declare module 'react-dropzone-component/src/__tests__/icon-test' {
  declare module.exports: any;
}

declare module 'react-dropzone-component/src/__tests__/react-dropzone-test' {
  declare module.exports: any;
}

declare module 'react-dropzone-component/src/__tests__/setup' {
  declare module.exports: any;
}

declare module 'react-dropzone-component/src/icon' {
  declare module.exports: any;
}

declare module 'react-dropzone-component/src/react-dropzone' {
  declare module.exports: any;
}

declare module 'react-dropzone-component/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dropzone-component/dist/react-dropzone.js' {
  declare module.exports: $Exports<'react-dropzone-component/dist/react-dropzone'>;
}
declare module 'react-dropzone-component/src/__tests__/icon-test.js' {
  declare module.exports: $Exports<'react-dropzone-component/src/__tests__/icon-test'>;
}
declare module 'react-dropzone-component/src/__tests__/react-dropzone-test.js' {
  declare module.exports: $Exports<'react-dropzone-component/src/__tests__/react-dropzone-test'>;
}
declare module 'react-dropzone-component/src/__tests__/setup.js' {
  declare module.exports: $Exports<'react-dropzone-component/src/__tests__/setup'>;
}
declare module 'react-dropzone-component/src/icon.js' {
  declare module.exports: $Exports<'react-dropzone-component/src/icon'>;
}
declare module 'react-dropzone-component/src/react-dropzone.js' {
  declare module.exports: $Exports<'react-dropzone-component/src/react-dropzone'>;
}
declare module 'react-dropzone-component/webpack.config.js' {
  declare module.exports: $Exports<'react-dropzone-component/webpack.config'>;
}
